config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :users, only: [:show] do
    resources :lists
  end

  resources :lists do
    resources :list_items
  end

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  has_many :list_items
  belongs_to :user
end

app/models/list_item.rb
class ListItem < ApplicationRecord
  belongs_to :list
end

app/models/user.rb
class User < ApplicationRecord
  has_many :lists
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, # :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/list_items_controller.rb
class ListItemsController < ApplicationController
  def index
  end

  def show
  end

  def create
    @list = List.find(params[:list_id])
    @list_item = @list.list_items.create(list_item_params)
    redirect_to @list
  end

  def destroy
  end

  def update
  end

  def new
  end
end

private
def list_item_params
  params.require(:list_item).permit(:text, :expires, :details)
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def new
    @list = current_user.lists.new
  end

  def create
    @list = current_user.lists.build
    puts params[:list][:is_public]
    @list.is_public = params[:list][:is_public] === "1" ? true : false
    @list.title = params[:list][:title]
    @list.save

    redirect_to user_path(current_user)
  end

  def update
  end

  def destroy
  end

  def index
  end

  def show
    @list = List.find(params[:id])
    @list_items = @list.list_items.all.order(expires: :asc)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    @lists = @user.lists.all
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :redirect

  def index
    @user = current_user if user_signed_in?
  end

  private

  def redirect
    redirect_to user_path(current_user) if user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/list_items_helper.rb
module ListItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_header.html.erb
<% if user_signed_in? %>
  <ul class="nav">
    <li class="nav-item">
      <%= link_to "Home", user_path(current_user), class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "New List", new_user_list_url(current_user), class: "nav-link" %>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Link</a>
    </li>
    <li class="nav-item">
      <a class="nav-link disabled" href="#">Disabled</a>
    </li>
    <li class="nav-item">
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
    </li>
  </ul>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PeerPressure</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>
    <%= render "layouts/header" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/list_items/create.html.erb
<h1>ListItems#create</h1>
<p>Find me in app/views/list_items/create.html.erb</p>

app/views/list_items/destroy.html.erb
<h1>ListItems#destroy</h1>
<p>Find me in app/views/list_items/destroy.html.erb</p>

app/views/list_items/index.html.erb
<h1>ListItems#index</h1>
<p>Find me in app/views/list_items/index.html.erb</p>

app/views/list_items/new.html.erb
<h1>ListItems#new</h1>
<p>Find me in app/views/list_items/new.html.erb</p>

app/views/list_items/show.html.erb
<h1>ListItems#show</h1>
<p>Find me in app/views/list_items/show.html.erb</p>

app/views/list_items/update.html.erb
<h1>ListItems#update</h1>
<p>Find me in app/views/list_items/update.html.erb</p>

app/views/lists/_form.html.erb
<%= form_with scope: :list, url: user_lists_path(current_user), local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
  <p>
    <%= form.label :is_public %><br>
    <%= form.check_box :is_public? %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/lists/create.html.erb
<h1>Lists#create</h1>
<p>Find me in app/views/lists/create.html.erb</p>

app/views/lists/destroy.html.erb
<h1>Lists#destroy</h1>
<p>Find me in app/views/lists/destroy.html.erb</p>

app/views/lists/index.html.erb
<h1>Lists#index</h1>
<p>Find me in app/views/lists/index.html.erb</p>

app/views/lists/new.html.erb
<%= form_with scope: :list, url: user_lists_path, local: true do |form| %>

  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@list.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @list.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :is_public %><br>
    <%= form.check_box :is_public? %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/lists/show.html.erb
<div class="row">
  <h1>
    <%= @list.title %>
  </h1>
</div>
<div class="row">
  <div class="col-sm">
    <h2>To Do</h2>
    <ol>
      <% @list_items.each do |item| %>
        <li>
          <h4>
            <%= item.text %>
          </h4>
          <p>
            <%= item.details %>
          </p>
          <small>
            Expires at <br>
            <%= item.expires %>
          </small>
        </li>
      <% end %>
    </ol>
  </div>
  <div clas="col-sm">
    <%= form_with scope: :list_item, url: list_list_items_path(@list), local: true do |form| %>
      <p>
        <%= form.label :list_item_name %><br>
        <%= form.text_field :text %>
      </p>
      <p>
        <%= form.label :details %><br>
        <%= form.text_field :details %>
      </p>
      <p>
        <%= form.label :do_by %><br>
        <%= datetime_select :list_item, :expires %>
      </p>
      <p>
        <%= form.submit "Add List Item" %>
      </p>
    <% end %>
  </div>
</div>

app/views/lists/update.html.erb
<h1>Lists#update</h1>
<p>Find me in app/views/lists/update.html.erb</p>

app/views/users/show.html.erb
<div class="row">
  <h1>My Home Page</h1>
</div>
<div class="row">
  <div class="col-sm">
    <h2>My Lists</h2>
    <ul>
      <% @lists.each do |list| %>
        <li>
          <p>
            <%= link_to list.title, list_path(list)  %>
          </p>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="col-sm">
    <%= render "lists/form" %>
  </div>
</div>

app/views/welcome/index.html.erb
<h1>Welcome to Peer Pressure</h1>
<div>
  <button>
    <%= link_to "Sign in", new_user_session_path %>
  </button>
  <button>
    <%= link_to "Sign up", new_user_registration_path %>
  </button>
</div>